### ISSUE TITLE
Watch Resource - support for Property and Path Filters

### ISSUE THREAD

**Issue by josh-barker-coles** [jfrog/terraform-provider-xray#3]
I'd like to use this provider for the watch support, but we need the include/exclude filters.

I've tested jfrog/terraform-provider-artifactory#36  and also found that:
- Property filters are not supported
- Resource documentation is missing

I'd be happy to contribute, but it's unclear as to how the schema should be defined to support the filters.

One potential option would be to name specific filter types - `property_filter` and `path_filter`, but this goes against the generic `filters` block.

```hcl
resource "xray_watch" "test" {
	name  = "%s"
	description = "%s"
	resources {
		type = "repository"
		name = "%s"
		bin_mgr_id = "%s"
		filters {
			type = "package-type"
			value = "%s"
		}
                property_filter { # 1 or more of these can be defined
                  key = "someKey"  # required field
                  value = "someValue" # required field
                }
                path_filter { # 0 or 1 of these can be defined.
                  exclude_patterns = ["some/path"] # default value of []
                  include_patterns = ["some/path"] # default value of []
                }
	}
	assigned_policies {
		name = xray_policy.test.name
		type = "security"
	}
}
```

Personally, I would consider changing the interface and have a specific filter parameters for each filter type, i.e. `package_type`, etc, as there are quite a few filter options because:
- the filter `type` string isn't clear and obvious. For example, the path filter for builds is `ant-patterns` but for repositories it is `path-ant-patterns`. 
- There are different filters that apply to a `repository` or a `build`. I'm not sure how obvious/helpful the error message that artifactory/xray returns.

You can go to https://github.com/jfrog/terraform-provider-artifactory/issues/6 to view some fuller examples.

**Comment by danielmkn** [comment]
Unfortunately, `ant-patterns` are now supported by only the Project filter (see Sample 7 in the [official API documentation](https://www.jfrog.com/confluence/display/JFROG/Xray+REST+API#XrayRESTAPI-CreateWatch)). 
So, there is no public API that supports filtering repositories or builds filtering for the Watch by exclude/include patterns.

**Comment by danielmkn** [comment]
@josh-barker-coles, it's been a while, but looks like we have a solution now, we added `path_ant_filter` attribute, example: 
```
 watch_resource {
    type       = "repository"
    bin_mgr_id = "default"
    name       = "your-repository-name"
    repo_type  = "local"

    path_ant_filter {
      exclude_patterns = ["**/*.md"]
      include_patterns = ["**/*.js"]
    }
  }

**Comment by gavinclarkeuk** [comment]
@danielmkn can this be reopened? I don't see how the `path_ant_filter` can be used to implement a property filter.

I imagine being able to define a property filter something like this:
```
	filters {
		type = "property"
		key = "team"
		value = "my-team"
	}
```

This seems to be inline with the API representation of these filters.

Also worth noting that currently if you try importing a watch with property filters defined on it, it causes the provider to crash.

```
Stack trace from the terraform-provider-xray_v1.9.10 plugin:

panic: set item just set doesn't exist

goroutine 60 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setSet(0x140005aed50, {0x140002d0f50, 0x1, 0x1}, {0x104964dc0, 0x140005b98d8}, 0x14000466b40)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/field_writer_map.go:327 +0x7fc
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0x140005aed50, {0x140002d0f50, 0x1, 0x1}, {0x104964dc0, 0x140005b98d8})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/field_writer_map.go:107 +0x124
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).WriteField(0x140005aed50, {0x140002d0f50, 0x1, 0x1}, {0x104964dc0, 0x140005b98d8})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/field_writer_map.go:89 +0x390
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).Set(0x140005a9700, {0x1047e5e9c, 0xe}, {0x104964dc0, 0x140005b98d8})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource_data.go:227 +0x20c
github.com/jfrog/terraform-provider-xray/pkg/xray.packWatch({0x104a84d90, 0x140004dab40}, {{0x0, 0x0}, {{0x1400019b730, 0xb}, {0x14000146780, 0x14}, 0x1}, {{0x140002984e0, ...}}, ...}, ...)
        github.com/jfrog/terraform-provider-xray/pkg/xray/watches.go:324 +0x228
github.com/jfrog/terraform-provider-xray/pkg/xray.resourceXrayWatchRead({0x104a84d90, 0x140004dab40}, 0x140005a9700, {0x104a74660?, 0x140000d21e0})
        github.com/jfrog/terraform-provider-xray/pkg/xray/watches.go:389 +0x4f0
github.com/jfrog/terraform-provider-shared/util.applyTelemetry.func1({0x104a84d90?, 0x140004dab40}, 0x10525c5b8?, {0x104a74660?, 0x140000d21e0})
        github.com/jfrog/terraform-provider-shared@v1.8.0/util/util.go:225 +0x1d4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x14000315880, {0x104a84dc8, 0x140002781b0}, 0xd?, {0x104a74660, 0x140000d21e0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:724 +0xec
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x14000315880, {0x104a84dc8, 0x140002781b0}, 0x140005a1ad0, {0x104a74660, 0x140000d21e0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:1015 +0x46c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x14000317998, {0x104a84d20?, 0x140002b5440?}, 0x140002b54c0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/grpc_provider.go:613 +0x40c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x140003a37c0, {0x104a84dc8?, 0x140000c5800?}, 0x140004da600)
        github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:746 +0x3b8
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x104a50380?, 0x140003a37c0}, {0x104a84dc8, 0x140000c5800}, 0x140004da5a0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x174
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000328700, {0x104a87768, 0x14000429860}, 0x140006498c0, 0x1400048a510, 0x104efe8f0, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1282 +0xb3c
google.golang.org/grpc.(*Server).handleStream(0x14000328700, {0x104a87768, 0x14000429860}, 0x140006498c0, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1619 +0x840
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.45.0/server.go:921 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.45.0/server.go:919 +0x298

Error: The terraform-provider-xray_v1.9.10 plugin crashed!
```

**Comment by danielmkn** [comment]
@gavinclarkeuk we will take a look.

**Comment by alexhung** [comment]
@gavinclarkeuk I've created a new issue to add support for the mime-type and property filters: https://github.com/jfrog/terraform-provider-xray/issues/107
